### PR TITLE
Updated FAQ for question on floating point anamolies. Resolve #2

### LINKED ISSUE #2: Add a question+answer about "I have problems with floating point value operations."
We get asked a lot about floating point operations and why they don't work as expected. We should give some examples for floating point pitfalls and also link to http://floating-point-gui.de/ .

### PR DESCRIPTION
**Pull request by hari-sikchi**
Updated FAQ for question on floating point anamolies

### CODE REVIEW

**Comment by Zarthus** [comment]
While the text looks good in vim, it's not well-written markdown. You should end sentences (that should have a newline) with either two spaces or an additional enter.

I would also put a space between punctuation, and maybe shorten the title a little bit. It's too long and specific.

This is what the file looks like in markdown: https://github.com/hari-sikchi/Freenode-programming-channel-FAQ/blob/ef87ae4cb0aac0957e798cf6033de2b4a501a254/FAQ.mdwn#i-have-a-problem-with-floating-point-numbersi-tried-adding-two-numbers-05-and-03-and-instead-of-adding-up-to-perfect-08-output-was-0800000000000000004why-does-this-happen

I also think the "resolve $id" needs to be in the commit itself for github to autoclose the issue, or in the PR body to make a reference.

**Comment by shlomif** [comment]
@hari-sikchi : in addition to @Zarthus comments:
1. The example in the title is too specific.
2. There are other cases of floating point problems such as "a + b == a" or addition not always being associative ("a + (b+ c) != (a + b) +c"). You should cover them as well.
3. You misspelled 'problems' in one case.

**Comment by hari-sikchi** [comment]
I ll look in to it and make the changes

**Comment by hari-sikchi** [comment]
@shlomif Added changes

**Comment by shlomif** [comment]
Thanks @hari-sikchi ! I've merged it, but will still need to do some corrections there.

**Pull request merged**
